name: wildfire_indicator
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - rasterio
  - gdal
  - geopandas
  - affine
  - folium
  - branca
  - numba
  - pypdf
  - pycountry
  - pip
  - pip:
    - mapclassify
    - pymupdf
    - pillow          # Für fehlerfreie Bildverarbeitung auf dem Mac
    - matplotlib      # Ebenfalls hierhin verschoben, um Abhängigkeitskonflikte zu vermeiden
    - openpyxl