name: ecological-value
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - rasterio
  - gdal
  - geopandas
  - affine
  - matplotlib
  - pillow
  - folium
  - branca
  - numba
  - mapclassify
  - pip
  - pip:
    - mapclassify   # conda-forge version sometimes lags